var hierarchy =
[
    [ "Achievement", "class_voxel_busters_1_1_native_plugins_1_1_achievement.html", null ],
    [ "AchievementDescription", "class_voxel_busters_1_1_native_plugins_1_1_achievement_description.html", null ],
    [ "AddressBook", "class_voxel_busters_1_1_native_plugins_1_1_address_book.html", null ],
    [ "AddressBookContact", "class_voxel_busters_1_1_native_plugins_1_1_address_book_contact.html", null ],
    [ "GameServicesSettings.AndroidSettings", "class_voxel_busters_1_1_native_plugins_1_1_game_services_settings_1_1_android_settings.html", null ],
    [ "MediaLibrarySettings.AndroidSettings", "class_voxel_busters_1_1_native_plugins_1_1_media_library_settings_1_1_android_settings.html", null ],
    [ "BillingSettings.AndroidSettings", "class_voxel_busters_1_1_native_plugins_1_1_billing_settings_1_1_android_settings.html", null ],
    [ "NetworkConnectivitySettings.AndroidSettings", "class_voxel_busters_1_1_native_plugins_1_1_network_connectivity_settings_1_1_android_settings.html", null ],
    [ "NotificationServiceSettings.AndroidSettings", "class_voxel_busters_1_1_native_plugins_1_1_notification_service_settings_1_1_android_settings.html", null ],
    [ "ApplicationSettings", "class_voxel_busters_1_1_native_plugins_1_1_application_settings.html", null ],
    [ "Billing", "class_voxel_busters_1_1_native_plugins_1_1_billing.html", null ],
    [ "BillingProduct", "class_voxel_busters_1_1_native_plugins_1_1_billing_product.html", null ],
    [ "BillingSettings", "class_voxel_busters_1_1_native_plugins_1_1_billing_settings.html", null ],
    [ "BillingTransaction", "class_voxel_busters_1_1_native_plugins_1_1_billing_transaction.html", null ],
    [ "CrossPlatformNotification", "class_voxel_busters_1_1_native_plugins_1_1_cross_platform_notification.html", null ],
    [ "NetworkConnectivitySettings.EditorSettings", "class_voxel_busters_1_1_native_plugins_1_1_network_connectivity_settings_1_1_editor_settings.html", null ],
    [ "GameServices", "class_voxel_busters_1_1_native_plugins_1_1_game_services.html", null ],
    [ "GameServicesSettings", "class_voxel_busters_1_1_native_plugins_1_1_game_services_settings.html", null ],
    [ "BillingSettings.iOSSettings", "class_voxel_busters_1_1_native_plugins_1_1_billing_settings_1_1i_o_s_settings.html", null ],
    [ "NotificationServiceSettings.iOSSettings", "class_voxel_busters_1_1_native_plugins_1_1_notification_service_settings_1_1i_o_s_settings.html", null ],
    [ "Leaderboard", "class_voxel_busters_1_1_native_plugins_1_1_leaderboard.html", null ],
    [ "MediaLibrary", "class_voxel_busters_1_1_native_plugins_1_1_media_library.html", null ],
    [ "MediaLibrarySettings", "class_voxel_busters_1_1_native_plugins_1_1_media_library_settings.html", null ],
    [ "NetworkConnectivity", "class_voxel_busters_1_1_native_plugins_1_1_network_connectivity.html", null ],
    [ "NetworkConnectivitySettings", "class_voxel_busters_1_1_native_plugins_1_1_network_connectivity_settings.html", null ],
    [ "NotificationService", "class_voxel_busters_1_1_native_plugins_1_1_notification_service.html", null ],
    [ "NotificationServiceSettings", "class_voxel_busters_1_1_native_plugins_1_1_notification_service_settings.html", null ],
    [ "RateMyApp", "class_voxel_busters_1_1_native_plugins_1_1_rate_my_app.html", null ],
    [ "Score", "class_voxel_busters_1_1_native_plugins_1_1_score.html", null ],
    [ "Sharing", "class_voxel_busters_1_1_native_plugins_1_1_sharing.html", null ],
    [ "Twitter", "class_voxel_busters_1_1_native_plugins_1_1_twitter.html", null ],
    [ "TwitterSession", "class_voxel_busters_1_1_native_plugins_1_1_twitter_session.html", null ],
    [ "TwitterSettings", "class_voxel_busters_1_1_native_plugins_1_1_twitter_settings.html", null ],
    [ "TwitterUser", "class_voxel_busters_1_1_native_plugins_1_1_twitter_user.html", null ],
    [ "UI", "class_voxel_busters_1_1_native_plugins_1_1_u_i.html", null ],
    [ "User", "class_voxel_busters_1_1_native_plugins_1_1_user.html", [
      [ "LocalUser", "class_voxel_busters_1_1_native_plugins_1_1_local_user.html", null ]
    ] ],
    [ "Utility", "class_voxel_busters_1_1_native_plugins_1_1_utility.html", null ],
    [ "UtilitySettings", "class_voxel_busters_1_1_native_plugins_1_1_utility_settings.html", null ],
    [ "WebView", "class_voxel_busters_1_1_native_plugins_1_1_web_view.html", null ],
    [ "WebViewMessage", "class_voxel_busters_1_1_native_plugins_1_1_web_view_message.html", null ]
];